export const receptionistCopy = {
  fr: {
    title: 'Sessions du jour',
    subtitle: 'Commandes opérationnelles de la clinique',
    reload: 'Actualiser',
    empty: 'Aucune session prévue pour cette journée.',
    loading: 'Chargement des sessions…',
    error: 'Impossible de charger les sessions.',
    add: 'Créer une session',
    doctor: 'Identifiant du médecin',
    start: 'Début',
    end: 'Fin',
    save: 'Créer',
    open: 'Ouvrir',
    pause: 'Pause',
    resume: 'Reprendre',
    close: 'Fermer',
    cancel: 'Annuler',
    delay: 'Retard',
    clear: 'Effacer',
    minutes: 'minutes',
    pending: 'Enregistrement…',
    promptCancel: 'Motif d’annulation (obligatoire)',
    promptDelay: 'Minutes de retard',
    statuses: {
      planned: 'Planifiée',
      open: 'Ouverte',
      paused: 'En pause',
      closed: 'Fermée',
      cancelled: 'Annulée',
    },
  },
  ar: {
    title: 'جلسات اليوم',
    subtitle: 'التحكم التشغيلي للعيادة',
    reload: 'تحديث',
    empty: 'لا توجد جلسات مبرمجة لهذا اليوم.',
    loading: 'جارٍ تحميل الجلسات…',
    error: 'تعذر تحميل الجلسات.',
    add: 'إنشاء جلسة',
    doctor: 'معرّف الطبيب',
    start: 'البداية',
    end: 'النهاية',
    save: 'إنشاء',
    open: 'فتح',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    close: 'إغلاق',
    cancel: 'إلغاء',
    delay: 'التأخير',
    clear: 'مسح',
    minutes: 'دقيقة',
    pending: 'جارٍ الحفظ…',
    promptCancel: 'سبب الإلغاء (مطلوب)',
    promptDelay: 'عدد دقائق التأخير',
    statuses: {
      planned: 'مبرمجة',
      open: 'مفتوحة',
      paused: 'متوقفة مؤقتًا',
      closed: 'مغلقة',
      cancelled: 'ملغاة',
    },
  },
};
