export const receptionistCopy = {
  fr: {
    title: 'Sessions du jour',
    subtitle: 'Commandes opérationnelles de la clinique',
    reload: 'Actualiser',
    empty: 'Aucune session prévue pour cette journée.',
    loading: 'Chargement des sessions…',
    error: 'Impossible de charger les sessions.',
    add: 'Créer une session',
    doctor: 'Identifiant du médecin',
    start: 'Début',
    end: 'Fin',
    save: 'Créer',
    open: 'Ouvrir',
    pause: 'Pause',
    resume: 'Reprendre',
    close: 'Fermer',
    cancel: 'Annuler',
    delay: 'Retard',
    clear: 'Effacer',
    minutes: 'minutes',
    pending: 'Enregistrement…',
    promptCancel: 'Motif d’annulation (obligatoire)',
    promptDelay: 'Minutes de retard',
    walkIns: 'Patients sans rendez-vous',
    queueTitle: 'File des patients sans rendez-vous',
    queueSubtitle: 'Inscription à l’accueil, avec ou sans coordonnées',
    backSessions: 'Retour aux sessions',
    addWalkIn: 'Ajouter un patient',
    guestName: 'Nom à l’accueil',
    phoneOptional: 'Téléphone (facultatif)',
    emailOptional: 'E-mail (facultatif)',
    contactOptionalHint:
      'Les coordonnées sont facultatives. Un patient sans téléphone reste entièrement pris en charge à la clinique.',
    queueLoading: 'Chargement de la file…',
    queueError: 'Impossible de charger ou mettre à jour la file.',
    noWaiting: 'Aucun patient en attente pour cette session.',
    publicLabel: 'Identifiant d’affichage',
    contactOnFile: 'Coordonnées disponibles',
    noContact: 'Sans coordonnées',
    statuses: {
      planned: 'Planifiée',
      open: 'Ouverte',
      paused: 'En pause',
      closed: 'Fermée',
      cancelled: 'Annulée',
    },
  },
  ar: {
    title: 'جلسات اليوم',
    subtitle: 'التحكم التشغيلي للعيادة',
    reload: 'تحديث',
    empty: 'لا توجد جلسات مبرمجة لهذا اليوم.',
    loading: 'جارٍ تحميل الجلسات…',
    error: 'تعذر تحميل الجلسات.',
    add: 'إنشاء جلسة',
    doctor: 'معرّف الطبيب',
    start: 'البداية',
    end: 'النهاية',
    save: 'إنشاء',
    open: 'فتح',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    close: 'إغلاق',
    cancel: 'إلغاء',
    delay: 'التأخير',
    clear: 'مسح',
    minutes: 'دقيقة',
    pending: 'جارٍ الحفظ…',
    promptCancel: 'سبب الإلغاء (مطلوب)',
    promptDelay: 'عدد دقائق التأخير',
    walkIns: 'المرضى بدون موعد',
    queueTitle: 'قائمة المرضى بدون موعد',
    queueSubtitle: 'تسجيل من الاستقبال مع أو بدون معلومات اتصال',
    backSessions: 'العودة إلى الجلسات',
    addWalkIn: 'إضافة مريض',
    guestName: 'الاسم لدى الاستقبال',
    phoneOptional: 'الهاتف (اختياري)',
    emailOptional: 'البريد الإلكتروني (اختياري)',
    contactOptionalHint:
      'معلومات الاتصال اختيارية. يبقى المريض بدون هاتف قابلاً للخدمة بالكامل داخل العيادة.',
    queueLoading: 'جارٍ تحميل قائمة الانتظار…',
    queueError: 'تعذر تحميل أو تحديث قائمة الانتظار.',
    noWaiting: 'لا يوجد مرضى في الانتظار لهذه الجلسة.',
    publicLabel: 'رمز العرض',
    contactOnFile: 'معلومات الاتصال متوفرة',
    noContact: 'بدون معلومات اتصال',
    statuses: {
      planned: 'مبرمجة',
      open: 'مفتوحة',
      paused: 'متوقفة مؤقتًا',
      closed: 'مغلقة',
      cancelled: 'ملغاة',
    },
  },
};
