export const receptionistCopy = {
  fr: {
    title: 'Sessions du jour',
    subtitle: 'Commandes opérationnelles de la clinique',
    reload: 'Actualiser',
    empty: 'Aucune session prévue pour cette journée.',
    loading: 'Chargement des sessions…',
    error: 'Impossible de charger les sessions.',
    add: 'Créer une session',
    doctor: 'Identifiant du médecin',
    start: 'Début',
    end: 'Fin',
    save: 'Créer',
    open: 'Ouvrir',
    pause: 'Pause',
    resume: 'Reprendre',
    close: 'Fermer',
    cancel: 'Annuler',
    delay: 'Retard',
    delayMinutes: 'Minutes de retard',
    delayRange: 'Nombre entier de 1 à 720 minutes',
    delayInvalid: 'Le retard doit être un nombre entier de 1 à 720 minutes.',
    clear: 'Effacer',
    minutes: 'minutes',
    pending: 'Enregistrement…',
    promptCancel: 'Motif d’annulation (obligatoire)',
    promptDelay: 'Minutes de retard',
    walkIns: 'Patients sans rendez-vous',
    queueTitle: 'File des patients sans rendez-vous',
    queueSubtitle: 'Inscription à l’accueil, avec ou sans coordonnées',
    backSessions: 'Retour aux sessions',
    addWalkIn: 'Ajouter un patient',
    guestName: 'Nom à l’accueil',
    phoneOptional: 'Téléphone (facultatif)',
    emailOptional: 'E-mail (facultatif)',
    patientLanguage: 'Langue préférée du patient',
    patientLanguageArabic: 'Arabe',
    patientLanguageFrench: 'Français',
    contactOptionalHint:
      'Les coordonnées sont facultatives. Un patient sans téléphone reste entièrement pris en charge à la clinique.',
    queueLoading: 'Chargement de la file…',
    queueError: 'Impossible de charger ou mettre à jour la file.',
    noWaiting: 'Aucun patient en attente pour cette session.',
    publicLabel: 'Identifiant d’affichage',
    contactOnFile: 'Coordonnées disponibles',
    noContact: 'Sans coordonnées',
    checkIn: 'Enregistrer l’arrivée',
    call: 'Appeler',
    noShow: 'Absent',
    cancelEntry: 'Annuler le passage',
    startConsultation: 'Démarrer la consultation',
    completeConsultation: 'Terminer la consultation',
    queueReason: 'Motif opérationnel (obligatoire)',
    registrationOrder: 'Inscription',
    priorityOrder: 'Ordre de service',
    reorderAudited: 'Prioriser / réordonner (audité)',
    reorderPosition: 'Nouvelle position de service',
    reorderReason: 'Motif opérationnel obligatoire (cette action est auditée)',
    reorderInvalid: 'La position doit être un nombre entier positif.',
    patientCancellation:
      'Confirmer : annulation demandée par le patient ? Annuler = décision de la clinique.',
    queueStatuses: {
      waiting: 'En attente',
      checked_in: 'Arrivé',
      called: 'Appelé',
      in_consultation: 'En consultation',
      completed: 'Terminé',
      cancelled: 'Annulé',
      no_show: 'Absent',
    },
    statuses: {
      planned: 'Planifiée',
      open: 'Ouverte',
      paused: 'En pause',
      closed: 'Fermée',
      cancelled: 'Annulée',
    },
  },
  ar: {
    title: 'جلسات اليوم',
    subtitle: 'التحكم التشغيلي للعيادة',
    reload: 'تحديث',
    empty: 'لا توجد جلسات مبرمجة لهذا اليوم.',
    loading: 'جارٍ تحميل الجلسات…',
    error: 'تعذر تحميل الجلسات.',
    add: 'إنشاء جلسة',
    doctor: 'معرّف الطبيب',
    start: 'البداية',
    end: 'النهاية',
    save: 'إنشاء',
    open: 'فتح',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    close: 'إغلاق',
    cancel: 'إلغاء',
    delay: 'التأخير',
    delayMinutes: 'دقائق التأخير',
    delayRange: 'عدد صحيح من 1 إلى 720 دقيقة',
    delayInvalid: 'يجب أن يكون التأخير عددًا صحيحًا من 1 إلى 720 دقيقة.',
    clear: 'مسح',
    minutes: 'دقيقة',
    pending: 'جارٍ الحفظ…',
    promptCancel: 'سبب الإلغاء (مطلوب)',
    promptDelay: 'عدد دقائق التأخير',
    walkIns: 'المرضى بدون موعد',
    queueTitle: 'قائمة المرضى بدون موعد',
    queueSubtitle: 'تسجيل من الاستقبال مع أو بدون معلومات اتصال',
    backSessions: 'العودة إلى الجلسات',
    addWalkIn: 'إضافة مريض',
    guestName: 'الاسم لدى الاستقبال',
    phoneOptional: 'الهاتف (اختياري)',
    emailOptional: 'البريد الإلكتروني (اختياري)',
    patientLanguage: 'لغة المريض المفضلة',
    patientLanguageArabic: 'العربية',
    patientLanguageFrench: 'الفرنسية',
    contactOptionalHint:
      'معلومات الاتصال اختيارية. يبقى المريض بدون هاتف قابلاً للخدمة بالكامل داخل العيادة.',
    queueLoading: 'جارٍ تحميل قائمة الانتظار…',
    queueError: 'تعذر تحميل أو تحديث قائمة الانتظار.',
    noWaiting: 'لا يوجد مرضى في الانتظار لهذه الجلسة.',
    publicLabel: 'رمز العرض',
    contactOnFile: 'معلومات الاتصال متوفرة',
    noContact: 'بدون معلومات اتصال',
    checkIn: 'تسجيل الوصول',
    call: 'نداء',
    noShow: 'لم يحضر',
    cancelEntry: 'إلغاء الدور',
    startConsultation: 'بدء الاستشارة',
    completeConsultation: 'إنهاء الاستشارة',
    queueReason: 'السبب التشغيلي (مطلوب)',
    registrationOrder: 'ترتيب التسجيل',
    priorityOrder: 'ترتيب الخدمة',
    reorderAudited: 'تقديم / إعادة ترتيب (مدقّق)',
    reorderPosition: 'موضع الخدمة الجديد',
    reorderReason: 'سبب تشغيلي إلزامي (يتم تدقيق هذا الإجراء)',
    reorderInvalid: 'يجب أن يكون الموضع عددًا صحيحًا موجبًا.',
    patientCancellation:
      'تأكيد: هل طلب المريض الإلغاء؟ اختر إلغاء إذا كان القرار من العيادة.',
    queueStatuses: {
      waiting: 'في الانتظار',
      checked_in: 'حاضر',
      called: 'تم النداء',
      in_consultation: 'في الاستشارة',
      completed: 'مكتمل',
      cancelled: 'ملغى',
      no_show: 'لم يحضر',
    },
    statuses: {
      planned: 'مبرمجة',
      open: 'مفتوحة',
      paused: 'متوقفة مؤقتًا',
      closed: 'مغلقة',
      cancelled: 'ملغاة',
    },
  },
};
