language: en-US
reviews:
  profile: assertive
  suggested_reviewers: false
  auto_assign_reviewers: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - "^main$"
